/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WydarzeniaEventIdRouteImport } from './routes/wydarzenia/$eventId'
import { Route as WydarzeniaDodajIndexRouteImport } from './routes/wydarzenia/dodaj/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WydarzeniaEventIdRoute = WydarzeniaEventIdRouteImport.update({
  id: '/wydarzenia/$eventId',
  path: '/wydarzenia/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const WydarzeniaDodajIndexRoute = WydarzeniaDodajIndexRouteImport.update({
  id: '/wydarzenia/dodaj/',
  path: '/wydarzenia/dodaj/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wydarzenia/$eventId': typeof WydarzeniaEventIdRoute
  '/wydarzenia/dodaj': typeof WydarzeniaDodajIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wydarzenia/$eventId': typeof WydarzeniaEventIdRoute
  '/wydarzenia/dodaj': typeof WydarzeniaDodajIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wydarzenia/$eventId': typeof WydarzeniaEventIdRoute
  '/wydarzenia/dodaj/': typeof WydarzeniaDodajIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wydarzenia/$eventId' | '/wydarzenia/dodaj'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wydarzenia/$eventId' | '/wydarzenia/dodaj'
  id: '__root__' | '/' | '/wydarzenia/$eventId' | '/wydarzenia/dodaj/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WydarzeniaEventIdRoute: typeof WydarzeniaEventIdRoute
  WydarzeniaDodajIndexRoute: typeof WydarzeniaDodajIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydarzenia/$eventId': {
      id: '/wydarzenia/$eventId'
      path: '/wydarzenia/$eventId'
      fullPath: '/wydarzenia/$eventId'
      preLoaderRoute: typeof WydarzeniaEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wydarzenia/dodaj/': {
      id: '/wydarzenia/dodaj/'
      path: '/wydarzenia/dodaj'
      fullPath: '/wydarzenia/dodaj'
      preLoaderRoute: typeof WydarzeniaDodajIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WydarzeniaEventIdRoute: WydarzeniaEventIdRoute,
  WydarzeniaDodajIndexRoute: WydarzeniaDodajIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
